### ISSUE TITLE
Wrong type of `path` in `HttpRestRequest`

### ISSUE THREAD

**Issue by dkokic** [spacez320/dart-rest#3]
Dart SDK 1.9.3

```
Uncaught Error: type 'Uri' is not a subtype of type 'String' of 'path'.
Stack Trace:
#0      HttpRestRequest.HttpRestRequest (package:rest/http_rest_request.dart:18:30)
#1      HttpRestRequest.HttpRestRequest.fromRequest (package:rest/http_rest_request.dart:24:5)
#2      HttpRest.act (package:rest/http_rest.dart:148:26)
#3      HttpRest.resolve (package:rest/http_rest.dart:102:27)
```

**Comment by spacez320** [comment]
I'm not sure what you mean by "wrong type of `post`". The stack trace doesn't
appear to be complaining about the request method, but that the path argument
is a `Uri` and not a string, and it doesn't know how to construct `HttpRestRequest`.

I did a simple test on SDK 1.9.3 to see if I could replicate the problem;

```dart
HttpServer.bind(address, port).then((server) {
  server.listen((HttpRequest request) {

    // Does request.uri automatically convert to a string?
    print("Request uri ::: ${request.uri}");

    // What does Dart think request.uri's Class is?
    if(request.uri is Uri) {
      print('Request uri type is Uri');
    } else if(request.uri is String) {
      print('Request uri type is String');
    }

    // What if we assign it to a String variable?
    String test = request.uri;
    print('String conversion ::: ${test}');
  });
});
```

The above doesn't stack trace and gives output I would expect;

```
> Request uri ::: /foo/bar
> Request uri type is Uri
> String conversion ::: /foo/bar
```

So if I'm not making any mistakes in analysis, can you show me an example of
how you're arriving to the above error? Are you using something other than
`HttpServer` in `dart:io`? Or could this be the result of dart2js or something compilation related?

**Comment by dkokic** [comment]
No `dart2js` involved.
You are right `request.uri is Uri`. The problem is `String path;` in `http_rest_request.dart`

**Comment by spacez320** [comment]
Can you paste some example code that replicates the issue? Thanks.

**Comment by dkokic** [comment]
I believe the problem disappears if you are not running in the checked mode. Never the less there is a type mismatch.

Here my code which is a copy of your example:
```

import 'dart:io';
import 'package:rest/http_rest.dart' show HttpRest, HttpRestRoute, HttpRestResponse;
//import 'package:rest_frame/rest_frame.dart';

main() {
  startServer();
}

void startServer() {
  // keys are regular expressions, or null
  var routes = {
    r"^foo": {
      r"^bar$": {

        // the null key will allow a request for 'foo/bar'

        null: new HttpRestRoute({
          'GET': getFooBar               // a function called fooBar
        }),

        // this will match PUT requests of form 'foo/bar/\d+'

        r"\d+": new HttpRestRoute({
          'PUT': createFooBar         // a function called createFooBar
        }),

      },

      // this will match POST requests of form 'foo/bat'

      r"^bat$": new HttpRestRoute({
        'POST': fooBat                // a function called fooBat
      })
    }
  };

  HttpRest rest = new HttpRest(routes);

  //Router router = new Router();
  //router.get(getFooBar, "/foo/bar");

  HttpServer.bind('0.0.0.0', 8888)
  .then((HttpServer httpServer) {

    print('Server available on http://${httpServer.address.host}:${httpServer.port}');

    httpServer.listen((HttpRequest httpRequest) {
      print("Received ${httpRequest.method} ${httpRequest.uri.path}");
      rest.resolve(httpRequest);
      //router.route(httpRequest);
    });
  });
}

HttpRestResponse getFooBar() {
  print('getFooBar(): ...');
  return new HttpRestResponse().build(204, 'found a fooBar!\n');
}

      createFooBar() {
        return new HttpRestResponse().build(204, 'created a fooBar!\n');
      }

      fooBat() {
        return new HttpRestResponse().build(502, 'fooBat!\n');
      }

void handleApi(_) {
  print(_);
}
```
After running a unit test:
```

import 'dart:io';
import 'dart:convert';
import 'package:unittest/unittest.dart';

main() {
  group('REST server group', () {
    var homeserver_base_url = 'http://localhost:8888';
    HttpClient httpClient = new HttpClient();

    setUp(() {
      print('setUp(): ...');
    });

    test('Test request', () {
      print('test(): ...');
      httpClient.getUrl(Uri.parse('$homeserver_base_url/foo/bar'))
      .then((HttpClientRequest request) {
        // Optionally set up headers...
        // Optionally write to the request object...
        // Then call close.
        return request.close();
      })
      .then((HttpClientResponse response) {
        expect(response.statusCode, 204);
        response.transform(UTF8.decoder).listen((content) {
          print(content);
        });
      });
    });

  });
}
```
it is crashing the server with the following error:
```
Observatory listening on http://127.0.0.1:56703
Server available on http://0.0.0.0:8888
Received GET /foo/bar
Unhandled exception:
Uncaught Error: type 'Uri' is not a subtype of type 'String' of 'path'.
Stack Trace:
#0      HttpRestRequest.HttpRestRequest (package:rest/http_rest_request.dart:18:30)
#1      HttpRestRequest.HttpRestRequest.fromRequest (package:rest/http_rest_request.dart:24:5)
#2      HttpRest.act (package:rest/http_rest.dart:148:26)
#3      HttpRest.resolve (package:rest/http_rest.dart:102:24)
#4      startServer.<anonymous closure>.<anonymous closure> (file:///Users/kodra/Developer/Projects/dart/matrix.dart/bin/server.dart:50:12)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#9      _StreamController._add (dart:async/stream_controller.dart:570)
#10     _StreamController.add (dart:async/stream_controller.dart:516)
#11     _HttpServer._handleRequest (dart:io/http_impl.dart:2316)
#12     _HttpConnection._HttpConnection.<anonymous closure> (dart:io/http_impl.dart:2070)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#16     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#17     _StreamController._add (dart:async/stream_controller.dart:570)
#18     _StreamController.add (dart:async/stream_controller.dart:516)
#19     _HttpParser._headersEnd (dart:io/http_parser.dart:387)
#20     _HttpParser._doParse (dart:io/http_parser.dart:709)
#21     _HttpParser._parse (dart:io/http_parser.dart:330)
#22     _HttpParser._onData (dart:io/http_parser.dart:819)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#26     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#27     _StreamController._add (dart:async/stream_controller.dart:570)
#28     _StreamController.add (dart:async/stream_controller.dart:516)
#29     _Socket._onData (dart:io-patch/socket_patch.dart:1793)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#33     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#34     _StreamController._add (dart:async/stream_controller.dart:570)
#35     _StreamController.add (dart:async/stream_controller.dart:516)
#36     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1344)
#37     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:728)
#38     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#39     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```
So let's look into `http_rest_request.dart`
```
part of http_rest;

/**
 * A response to an HTTP REST request.
 */
class HttpRestRequest implements RestRequest {
  /// request uri
  final String path;
  /// request method
  final String verb;
  /// request headers
  final Map headers;

  /**
   * Generates an HTTP REST request.
   */
  const HttpRestRequest(this.path, this.verb, this.headers);

  /**
   * Generates an HTTP REST request from an HttpRequest.
   */
  const HttpRestRequest.fromRequest(HttpRequest request) :
    this(request.uri, request.method, request.headers);
}
```
As you can see, the `path` is defined as `String` and used in the constructor to assign the value from `request.uri` which is defined as Uri ... ergo `Uncaught Error: type 'Uri' is not a subtype of type 'String' of 'path'.`

**Comment by spacez320** [comment]
I believe this is fixed in 0cca10b6ee059d587bf0bfe787a5829e7991af07

Turns out I had completely forgotten about Dart's 'checked compilation' feature and the library was riddled with broken things.

One thing to note is that your endpoints will no longer call the factory-ish `build` method of `HttpRestResponse`, but should just create `HttpRestResponse` objects with the same arguments.

Example;

```dart
// change this
return HttpRestResponse.build(200, 'awesome');
// to this
return HttpRestResponse(200, 'awesome');
```

Can you confirm that things are working better? Thanks for your help.

**Comment by spacez320** [comment]
Closing this, as I believe we're good, but feel free to complain if you disagree.

**Comment by dkokic** [comment]
No complains ;-)
